### ISSUE TITLE
What is the state of the project?

### ISSUE THREAD

**Issue by bonndan** [Firehed/php7ize#8]
No updates in seven months and no description of the usage. I assume you are not following this path anymore?

**Comment by Firehed** [comment]
Hi @bonndan,

I no longer have an ongoing need to migrate code to PHP7 so haven't touched this in a while. There's a help function built-in to the command (run from the bin directory) that should cover the usage basics. 

I'm happy to look at contributions but probably will not be doing further development myself, as it covers my basic needs (primarily adding additional typehints)

**Comment by bonndan** [comment]
Good to know and thanks for the reply.
